### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by micahcochran** [karimbahgat/PyAgg#1]
Would it be easy to add Linux support?

I'm using this library to test PyCRS.

**Comment by karimbahgat** [comment]
Sorry for delay. Now that you mention it, I wonder if the .so file works for all of Unix (so Mac and Linux) (before I just assumed that Linux would require another type of file). So I made a quick update to the import code so that Linux and Mac will import the same .so file. 

So can you update your PyAgg package with the newest GitHub source code, and test if it works? I don't have a Linux to test it. 

Last resort, if the .so file doesn't work, you can try to compile aggdraw from scratch on your Linux, and with that you should be able to run PyAgg.

**Comment by karimbahgat** [comment]
@micahcochran in the updated version, did the .so file work on Linux?

**Comment by micahcochran** [comment]
No, but I'll try to give more details soon.

**Comment by micahcochran** [comment]
I've install this version of aggdraw, which appears to be somewhat maintained,   https://github.com/jakul/aggdraw

All of the tests have issues with the font names.  Like so:

```
micah@micah-VirtualBox:~/prj/PyAgg-master$ python2 legend_tester.py 
None
None
[<pyagg.legend.Symbol instance at 0xb5bc30cc>, <pyagg.legend.Symbol instance at 0xb5bc30ec>]
[<pyagg.legend.Symbol instance at 0xb5bc316c>, <pyagg.legend.Symbol instance at 0xb5bc31ac>]
[<pyagg.legend.Symbol instance at 0xb5bc320c>, <pyagg.legend.Symbol instance at 0xb5bc324c>]
[<pyagg.legend.SymbolGroup instance at 0xb5bc310c>, <pyagg.legend.SymbolGroup instance at 0xb5bc31cc>, <pyagg.legend.SymbolGroup instance at 0xb5bc326c>]
Traceback (most recent call last):
  File "legend_tester.py", line 70, in <module>
    legend.render().save("testlegend.png")
  File "/home/micah/prj/PyAgg-master/pyagg/legend.py", line 97, in render
    rensymbols = [s.render() for s in self.items]
  File "/home/micah/prj/PyAgg-master/pyagg/legend.py", line 30, in render
    rendered = self.type(**self.kwargs)
  File "legend_tester.py", line 42, in <lambda>
    legend.add_item(Symbol(lambda: label("SymbolGroup 3")))
  File "legend_tester.py", line 40, in label
    c.draw_text(text,(0,0),anchor="nw", textsize="40%")
  File "/home/micah/prj/PyAgg-master/pyagg/canvas.py", line 1857, in draw_text
    fontlocation = fonthelper.get_fontpath(options["font"])
  File "/home/micah/prj/PyAgg-master/pyagg/fonthelper.py", line 154, in get_fontpath
    raise Exception("Could not find the font specified. Font must be either a human-readable name, a filename with extension in the default font folder, or a full path to the font file location")
Exception: Could not find the font specified. Font must be either a human-readable name, a filename with extension in the default font folder, or a full path to the font file location
```

It is easy enough to do an platform.system() and pick an appropriate font name for the system.   In Linux, I've already tried changing the font names, and it still had the same issue.  Even when I put in the full path to the font file, it didn't work.

**Comment by karimbahgat** [comment]
Since you installed aggdraw on your own, should i assume the precompiled .so version didnt work on your linux after my patch?

This new problem is also likely related to linux. The font logic comes from the fonthelper.py file, which you can find here: https://github.com/karimbahgat/PyAgg/blob/master/pyagg/fonthelper.py

Fonthelper does indeed look for platform specific font locations, in the case of linux, it looks them up in the folder "/usr/share/fonts/truetype/", and you can also add additional folders with SYSFONTFOLDERS["linux"].append(folder). Any fonts in those location will be found if there is a match in their font name as specified in the file format, or in the filename plus file extension, or a full path to the file. Note that the input font parameter is lowercased, and i suspect that your linux maybe has a different font folder and that perhaps linux is case sensitive for filenames and paths. For the full path to work, the path you give must be true for os.path.lexists(), so maybe something you can doublecheck, with and without the filename lowercased. 

If lowercasing is the issue that should be an easy fix.
